### ISSUE TITLE
How to use the sortProperties option

### ISSUE THREAD

**Issue by DiegoAz** [aktanoff/sublime-stylus-supremacy#1]
Hi, it is possible to use the sortProperties option? if so, could you tell me how. Thanks

https://thisismanta.github.io/stylus-supremacy/#option-sort-properties

**Comment by aktanoff** [comment]
Hi, i have in plans to make an convenient options control, but currently i'm too busy.
So for now you can go to the Preferences - Browse Packages...
![image](https://user-images.githubusercontent.com/36963472/70395759-e700fa80-1a23-11ea-9ad1-5f6cd34a6410.png)

Then to the 'sublime-stylus-supremacy' folder, open 'stylussupremacy.js' file and replace everything with:
```
"use strict";
const getStdin = require("get-stdin");
const stylusSupremacy = require("stylus-supremacy");

(async () => {
	const data = await getStdin();

	const formattingOptions = {
		sortProperties: "alphabetical"
	};

	try {
		process.stdout.write(stylusSupremacy.format(data, formattingOptions));
	} catch (err) {
		throw err;
	}
})();
```
here you can change options on whatever you like
```
const formattingOptions = {
	sortProperties: "alphabetical"
};
```

I hope this helped you, have a good day!

**Comment by DiegoAz** [comment]
Hi, Thanks a lot for your help! It works as I wanted.

I am using in conjunction with a package called Hooks to apply stylus-supremacy every time I save.
